# Generated by Django 5.1.4 on 2025-01-08 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Valo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('tila', models.BooleanField(default=False)),
                ('huone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valot', to='valot.huone')),
            ],
        ),
        migrations.CreateModel(
            name='Tilaus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aika', models.DateTimeField(auto_now_add=True)),
                ('toiminto', models.CharField(choices=[('ON', 'Päällä'), ('OFF', 'Pois')], max_length=10)),
                ('valo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valot.valo')),
            ],
        ),
    ]
